Defaulting to user installation because normal site-packages is not writeable
Collecting google-cloud-aiplatform
  Using cached google_cloud_aiplatform-1.109.0-py2.py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1 in /usr/lib/python3/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform) (2.23.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/lib/python3/dist-packages (from google-cloud-aiplatform) (2.28.2)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/lib/python3/dist-packages (from google-cloud-aiplatform) (1.26.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-aiplatform) (5.29.5)
Requirement already satisfied: packaging>=14.3 in /usr/lib/python3/dist-packages (from google-cloud-aiplatform) (25.0)
Requirement already satisfied: google-cloud-storage<3.0.0,>=1.32.0 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-aiplatform) (2.19.0)
Requirement already satisfied: google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-aiplatform) (3.35.1)
Requirement already satisfied: google-cloud-resource-manager<3.0.0,>=1.3.3 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-aiplatform) (1.14.2)
Requirement already satisfied: shapely<3.0.0 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-aiplatform) (2.1.1)
Requirement already satisfied: google-genai<2.0.0,>=1.0.0 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-aiplatform) (1.30.0)
Requirement already satisfied: pydantic<3 in /usr/lib/python3/dist-packages (from google-cloud-aiplatform) (2.10.6)
Requirement already satisfied: typing_extensions in /usr/lib/python3/dist-packages (from google-cloud-aiplatform) (4.13.2)
Requirement already satisfied: docstring_parser<1 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-aiplatform) (0.17.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/lib/python3/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform) (1.66.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /usr/lib/python3/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform) (2.32.3)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /home/r/.local/lib/python3.13/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform) (1.71.2)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /home/r/.local/lib/python3.13/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform) (1.74.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform) (2.4.3)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform) (2.7.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/lib/python3/dist-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform) (2.9.0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-resource-manager<3.0.0,>=1.3.3->google-cloud-aiplatform) (0.14.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/r/.local/lib/python3.13/site-packages (from google-cloud-storage<3.0.0,>=1.32.0->google-cloud-aiplatform) (1.7.1)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/lib/python3/dist-packages (from google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (4.8.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/lib/python3/dist-packages (from google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (0.28.1)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/lib/python3/dist-packages (from google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (8.4.2+really8.4.1)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/lib/python3/dist-packages (from google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/lib/python3/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (1.3.1)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/lib/python3/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/lib/python3/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/lib/python3/dist-packages (from pydantic<3->google-cloud-aiplatform) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/lib/python3/dist-packages (from pydantic<3->google-cloud-aiplatform) (2.27.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/lib/python3/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform) (2.3.0)
Requirement already satisfied: numpy>=1.21 in /usr/lib/python3/dist-packages (from shapely<3.0.0->google-cloud-aiplatform) (2.2.4)
Using cached google_cloud_aiplatform-1.109.0-py2.py3-none-any.whl (7.9 MB)
Installing collected packages: google-cloud-aiplatform
Successfully installed google-cloud-aiplatform-1.109.0
